version: '1.0'

stages:
- Prepare
- Test
- Release

steps:
  main_clone:
    stage: Prepare
    title: clone repository
    type: git-clone
    git: cf_github
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_BRANCH}}

  test:
    stage: Test
    title: unit-tests
    image: quay.io/codefresh/golang-ci-helper:1.21.5
    commands:
    - make test-all
  
  ReleasingBinaries:
    stage: Release
    title: Create release in Github
    image: quay.io/codefresh/golang-ci-helper:1.21.5
    commands:
    - export VERSION=$(cat VERSION)
    - VERSION=$(if [[ ${VERSION:0:1} == "v" ]] ; then echo $VERSION; else echo "v${VERSION}"; fi )
    - gh release create --repo ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}} -t $VERSION -n $VERSION $VERSION
    when:
      branch:
        only:
        - master
