version: '1.0'

stages:
- Release

mode: parallel

steps:

  CreatingGitTag:
    title: Push tag to git
    image: codefresh/cli
    stage: Release
    commands:
    - export VERSION=$(cat VERSION)
    - git remote rm origin
    - git remote add origin https://${{GITHUB_TOKEN}}@github.com/codefresh-io/go-sdk.git
    - git tag v$VERSION
    - git push --tags
    fail_fast: false
    when:
      steps:
      - name: main_clone
      branch:
        only:
        - master
  
  ReleasingBinaries:
    title: Create release in Github
    image: goreleaser/goreleaser
    stage: Release
    working_directory: /go/src/github.com/codefresh-io/go-sdk
    binds:
    - ./go-sdk:/go/src/github.com/codefresh-io/go-sdk
    fail_fast: false
    commands:
    - goreleaser release -f .goreleaser.yml --rm-dist --skip-validate
    when:
      steps:
      - name: CreatingGitTag
        on:
        - finished
      branch:
        only:
        - master