// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	codefresh "github.com/codefresh-io/go-sdk/pkg/codefresh"
	mock "github.com/stretchr/testify/mock"
)

// IClusterAPI is an autogenerated mock type for the IClusterAPI type
type IClusterAPI struct {
	mock.Mock
}

// GetAccountClusters provides a mock function with given fields:
func (_m *IClusterAPI) GetAccountClusters() ([]*codefresh.ClusterMinified, error) {
	ret := _m.Called()

	var r0 []*codefresh.ClusterMinified
	if rf, ok := ret.Get(0).(func() []*codefresh.ClusterMinified); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*codefresh.ClusterMinified)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterCredentialsByAccountId provides a mock function with given fields: selector
func (_m *IClusterAPI) GetClusterCredentialsByAccountId(selector string) (*codefresh.Cluster, error) {
	ret := _m.Called(selector)

	var r0 *codefresh.Cluster
	if rf, ok := ret.Get(0).(func(string) *codefresh.Cluster); ok {
		r0 = rf(selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*codefresh.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
