// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	codefresh "github.com/codefresh-io/go-sdk/pkg/codefresh"
	mock "github.com/stretchr/testify/mock"
)

// IPipelineAPI is an autogenerated mock type for the IPipelineAPI type
type IPipelineAPI struct {
	mock.Mock
}

// List provides a mock function with given fields: qs
func (_m *IPipelineAPI) List(qs map[string]string) ([]*codefresh.Pipeline, error) {
	ret := _m.Called(qs)

	var r0 []*codefresh.Pipeline
	if rf, ok := ret.Get(0).(func(map[string]string) []*codefresh.Pipeline); ok {
		r0 = rf(qs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*codefresh.Pipeline)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(qs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *IPipelineAPI) Run(_a0 string, _a1 *codefresh.RunOptions) (string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, *codefresh.RunOptions) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *codefresh.RunOptions) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
