// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	codefresh "github.com/codefresh-io/go-sdk/pkg/codefresh"
	mock "github.com/stretchr/testify/mock"
)

// IProgressAPI is an autogenerated mock type for the IProgressAPI type
type IProgressAPI struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *IProgressAPI) Get(_a0 string) (*codefresh.Progress, error) {
	ret := _m.Called(_a0)

	var r0 *codefresh.Progress
	if rf, ok := ret.Get(0).(func(string) *codefresh.Progress); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*codefresh.Progress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
