// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	codefresh "github.com/codefresh-io/go-sdk/pkg/codefresh"
	mock "github.com/stretchr/testify/mock"
)

// ITokenAPI is an autogenerated mock type for the ITokenAPI type
type ITokenAPI struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, subject
func (_m *ITokenAPI) Create(name string, subject string) (*codefresh.Token, error) {
	ret := _m.Called(name, subject)

	var r0 *codefresh.Token
	if rf, ok := ret.Get(0).(func(string, string) *codefresh.Token); ok {
		r0 = rf(name, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*codefresh.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *ITokenAPI) List() ([]*codefresh.Token, error) {
	ret := _m.Called()

	var r0 []*codefresh.Token
	if rf, ok := ret.Get(0).(func() []*codefresh.Token); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*codefresh.Token)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
