// Code generated by mockery v1.1.1. DO NOT EDIT.

package mocks

import (
	context "context"

	codefresh "github.com/codefresh-io/go-sdk/pkg/codefresh"

	mock "github.com/stretchr/testify/mock"
)

// UsersAPI is an autogenerated mock type for the UsersAPI type
type UsersAPI struct {
	mock.Mock
}

// GetCurrent provides a mock function with given fields: ctx
func (_m *UsersAPI) GetCurrent(ctx context.Context) (*codefresh.User, error) {
	ret := _m.Called(ctx)

	var r0 *codefresh.User
	if rf, ok := ret.Get(0).(func(context.Context) *codefresh.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*codefresh.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
